from turtle import Turtle, Screen

t = Turtle()
t.hideturtle()
t.color("red")
t.begin_fill()
t.pensize(5)
t.left(50)
t.forward(133)
t.circle(50, 200)
t.right(140)
t.circle(50, 200)
t.forward(133)
t.end_fill()
screen = Screen()
screen.exitonclick()